language: android
jdk: oraclejdk8

android:
  components:
    - extra-android-m2repository
    - extra-android-support
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-27

env:
  global:
    - MALLOC_ARENA_MAX=2
    - GRADLE_OPTS="-Xmx4g"
    - ANDROID_SDKS=android-15
    - ANDROID_TARGET=android-15
  matrix:
    - TASK=build-and-lint
    - TASK=unit-tests
    - TASK=mocked-connected-tests

before_install:
  # Not always needed if Travis' platform-tools are up to date, but keeping for safety
  - echo yes | android update sdk -a --filter platform-tools --no-ui --force

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
  - if [ "$TASK" == "mocked-connected-tests" ]; then
      echo "Starting AVD for mocked connected tests";
      android-update-sdk --components=android-16;
      android-update-sdk --components=sys-img-armeabi-v7a-android-16 --accept-licenses='android-sdk-license-[0-9a-f]{8}';
      echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a --skin QVGA;
      emulator -avd test -no-audio -no-window &
    fi

script:
  - set -e # Exit and fail right away if any individual step fails
  - if [ "$TASK" == "build-and-lint" ]; then
      ./gradlew assembleDebug assembleRelease;
      ./gradlew checkstyle ktlint;
      ./gradlew lint || (grep -A20 -B2 'severity="Error"' */build/**/*.xml; exit 1);
      find . -iname "*XMLRPCClient*java" | xargs grep getSiteId && (echo "You should not use _getSiteId_ in a XMLRPClient, did you mean _selfHostedId_?" && exit 1) || return 0;
    elif [ "$TASK" == "unit-tests" ]; then
      ./gradlew example:assembleRelease example:testRelease;
    elif [ "$TASK" == "mocked-connected-tests" ]; then
      ./gradlew example:assembleDebug example:assembleDebugAndroidTest;
      android-wait-for-emulator;
      ./gradlew cAT -Pandroid.testInstrumentationRunnerArguments.package=org.wordpress.android.fluxc.mocked;
    fi
