version: 2.1

orbs:
  android: wordpress-mobile/android@0.0.21

commands:
  copy-gradle-properties:
    steps:
      - run:
          name: Setup gradle.properties
          command: cp example/gradle.properties-example example/gradle.properties

jobs:
  Lint:
    executor: 
      name: android/default
      api-version: "27"
    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: lint
      - copy-gradle-properties
      - run:
          name: Checkstyle
          command: ./gradlew --stacktrace checkstyle ktlint
      - run:
          name: Lint
          command: |
            ./gradlew --stacktrace lintRelease || (grep -A20 -B2 'severity="Error"' */build/**/*.xml; exit 1);
            find . -iname "*XMLRPCClient*java" | xargs grep getSiteId && (echo "You should not use _getSiteId_ in a XMLRPClient, did you mean _selfHostedId_?" && exit 1) || exit 0;
      - android/save-gradle-cache:
          cache-prefix: lint
      - store_artifacts:
          path: fluxc/build/reports
          destination: reports
  Unit Tests:
    executor: 
      name: android/default
      api-version: "27"
    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: unit-tests
      - copy-gradle-properties
      - run:
          name: Unit tests
          command: ./gradlew --stacktrace -PtestsMaxHeapSize=1536m example:testRelease
      - android/save-gradle-cache:
          cache-prefix: unit-tests
      - android/save-test-results
  Mocked Connected Tests:
    executor: 
      name: android/default
      api-version: "27"
    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: mocked-connected-tests
      - run:
          name: Build
          command: ./gradlew --stacktrace example:assembleDebug example:assembleDebugAndroidTest
      - run:
          name: Decrypt credentials
          command: openssl aes-256-cbc -md sha256 -d -in .firebase.secrets.json.enc -out .firebase.secrets.json -k "${FIREBASE_SECRETS_ENCRYPTION_KEY}"
      - android/firebase-test:
          key-file: .firebase.secrets.json
          results-history-name: CircleCI FluxC Mocked Tests
          type: instrumentation
          apk-path: example/build/outputs/apk/debug/example-debug.apk
          test-apk-path: example/build/outputs/apk/androidTest/debug/example-debug-androidTest.apk
          test-targets: package org.wordpress.android.fluxc.mocked
          device: model=Nexus5X,version=26,locale=en,orientation=portrait
          project: api-project-108380595987
          timeout: 10m
          no-record-video: true
      - android/save-gradle-cache:
          cache-prefix: mocked-connected-tests

workflows:
  fluxc:
    jobs:
      - Lint
      - Unit Tests
      - Mocked Connected Tests
